name: flutter_button
description: This packege help you for develop applications fast and clean. 
version: 0.0.4
# author: Ismael Shakverdiev <st.bahahd@gmail.com> 
homepage: https://github.com/theiskaa/flutter_button

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
